Change RPM Setting
frc-6901/2022-Code pull request #16
Opened 2022-03-11 00:01 UTC by PraneelSeth

Created a new branch that is a repository of 6901 main. This one is up to date with main and rebased/merged and everything with new shooter RPM management code.

2022-03-11 20:46 UTC, Piphi5 requested changes

2022-03-11 20:46 UTC, Piphi5 commented on src/main/java/frc/robot/Constants.java
> -    public static final int kShooterTestRPM = 1950;
Keep a variable like kShooterFenderRPM = 1950

2022-03-11 20:46 UTC, Piphi5 commented on src/main/java/frc/robot/RobotContainer.java
> +              m_shooter.setRPM(500);
Use the variable above here instead

2022-03-11 20:46 UTC, Piphi5 commented on src/main/java/frc/robot/subsystems/Shooter.java
>        new CANSparkMax(ShooterConstants.kRightShooterMotorPort, MotorType.kBrushless);
Change the port constants to leader follower instead of left and right

2022-03-13 19:53 UTC, PraneelSeth commented
I made the changes that you requested and everything is up to date with the frc6901 upstream

2022-03-14 21:17 UTC, Piphi5 approved these changes

2022-03-14 23:57 UTC, merged